spring.application.name=simplifier-server
management.endpoints.web.exposure.include=*
springdoc.api-docs.path=/api-docs

spring.datasource.url=jdbc:h2:file:/Users/oliverjochum/data/simplifierdb;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

